name: "Pull Request Size Labelling"
description: "A GitHub App built with Probot for adding size labels to PRs"
branding:
  icon: "git-pull-request"
  color: "purple"
runs:
  using: "node16"
  main: "dist/index.js"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    requried: true
